version: 2
updates:
- package-ecosystem: maven
  directory: "server"
  schedule:
    interval: daily
  ignore:
    # ignore Maven APIs/SPIs
    - dependency-name: org.apache.maven:*
- package-ecosystem: "github-actions"
  directory: ".github"
  schedule:
    interval: daily
