version: 2
updates:
    - package-ecosystem: github-actions
      directory: ".github"
      schedule:
          interval: daily
          time: "21:00"
    - package-ecosystem: maven
      directory: "server"
      schedule:
          interval: daily
          time: "21:00"
      ignore:
          # ignore Maven APIs/SPIs
          - dependency-name: org.apache.maven:*

