name: 📆 Update Date

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # You need to create your own token with commit rights
          ref: ${{ github.ref }} # The branch you want to commit to
      
      - name: Give Permissions
        run: git update-index --chmod=+x ./.github/updateDate.sh # if this line gives error, then run it locally

      - name: Update Files
        run: ./.github/workflows/updateDate.sh
        shell: bash
      
      - name: Update Date
        uses: ./.github/actions/push-changes
        with:
          message: 'feat: snapshot of deployed site'

        
